image:
  file: .gitpod.Dockerfile

# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
# We grab the dynamically created GITPOD_WORKSPACE_URL, add ports 3000/1, and create 
# the .env files necessary for Wasp Routing and CORS 
tasks:
  - command: |
      code .vscode/wasp-0.1.0.vsix
      echo "REACT_APP_API_URL=$(printenv | grep "^GITPOD_WORKSPACE_URL=" | cut -d "=" -f 2 | awk '{gsub("https://","https://3001-")} 1')" >> MyNewApp/.env.client
      echo "WASP_WEB_CLIENT_URL=$(printenv | grep "^GITPOD_WORKSPACE_URL=" | cut -d "=" -f 2 | awk '{gsub("https://","https://3000-")} 1')" >> MyNewApp/.env.server
      cd MyNewApp
      wasp db migrate-dev
      wasp start

ports:
  - port: 3000
    description: Web app
    onOpen: notify
  - port: 3001
    visibility: public
    description: Node.js server
    onOpen: ignore
